jobhub/src/main/java/com/packt/pfextensions/controller/LanguageController.java
package com.packt.pfextensions.controller;

import java.io.Serializable;
import java.util.LinkedHashMap;
import java.util.Locale;
import java.util.Map;
import java.util.ResourceBundle;

import javax.annotation.PostConstruct;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ManagedProperty;
import javax.faces.bean.RequestScoped;
import javax.faces.bean.SessionScoped;
import javax.faces.bean.ViewScoped;
import javax.faces.context.FacesContext;
import javax.faces.event.ValueChangeEvent;

@ManagedBean
@RequestScoped
public class LanguageController implements Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	private String localeCode;

	private static Map<String, Object> countries;
	ResourceBundle messageBundle;

	@ManagedProperty(value = "#{loginBean}")
	private LoginBean loginBean; // +setter
	static {
		countries = new LinkedHashMap<String, Object>();
		countries.put("English", Locale.ENGLISH); // label, value
		countries.put("Turkey", Locale.forLanguageTag("tr-TR"));
	}

	@PostConstruct
	public void init() {

	}

	public void countryLocaleCodeChanged(ValueChangeEvent e) {
		System.out.println("locale changed");

		String newLocaleValue = e.getNewValue().toString();

		// loop country map to compare the locale code
		for (Map.Entry<String, Object> entry : countries.entrySet()) {

			if (entry.getValue().toString().equals(newLocaleValue)) {

				FacesContext.getCurrentInstance().getViewRoot()
						.setLocale((Locale) entry.getValue());

			}
		}
		System.out.println("login scoped bean");

		messageBundle = ResourceBundle.getBundle("com.packt.messages",FacesContext.getCurrentInstance().getViewRoot().getLocale());
		String loginmessage=messageBundle.getString("login.login"); 
		loginBean.setLoginmessage(loginmessage);
	}

	public Map<String, Object> getCountriesInMap() {
		return countries;
	}

	public String getLocaleCode() {
		return localeCode;
	}

	public void setLocaleCode(String localeCode) {
		this.localeCode = localeCode;
	}

	public LoginBean getLoginBean() {
		return loginBean;
	}

	public void setLoginBean(LoginBean loginBean) {
		this.loginBean = loginBean;
	}

}

jobhub/src/main/webapp/templates/common/content.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html>
<ui:composition xmlns="http://www.w3.org/1999/xhtml"   
      xmlns:ui="http://java.sun.com/jsf/facelets">
 
		<h1>This is default primefaces extensions default content</h1>

</ui:composition>

jobhub/src/main/webapp/templates/common/footer.xhtml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:f="http://xmlns.jcp.org/jsf/core"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns:p="http://primefaces.org/ui"
	xmlns:pe="http://primefaces.org/ui/extensions">

<p:panel >
	<h:form id="footerForm">
		<div style="margin-left: 30%;">
			<p:commandLink value="#{msg['footer.aboutus']}"
				onclick="PF('$aboutusDialog').show()" styleClass="links"></p:commandLink>
			<p:spacer width="20" />
			<p:commandLink value="#{msg['footer.communication']}"
				oncomplete="$communicationDialog.show()" styleClass="links"></p:commandLink>
			<p:spacer width="20" />
			<p:commandLink value="#{msg['footer.privacy']}"
				oncomplete="$privacyDialog.show()" styleClass="links"></p:commandLink>
			<p:spacer width="20" />
			<p:commandLink value="#{msg['footer.disclaimer']}"
				oncomplete="$disclaimerDialog.show()" styleClass="links"></p:commandLink>
			<p:spacer width="20" />
			<p:commandLink value="#{msg['footer.help']}"
				oncomplete="$helpDialog.show()" styleClass="links"></p:commandLink>
			<p:spacer height="40" />
		</div>
		<p:separator style="margin-left:30%;margin-right:30%"></p:separator>
		<div style="margin-left: 36%">@CopyRight 2013 All rights
			reserved.</div>

		<p:dialog id="aboutusDialog" header="About us"
			widgetVar="$aboutusDialog" width="400" modal="true" dynamic="true">
			<h:outputText value="#{adminController.aboutus}" />
		</p:dialog>
		
		<p:dialog id="communicationDialog" header="Communication"
			widgetVar="$communicationDialog" width="400" modal="true"
			dynamic="true">
			<h:outputText value="#{adminController.communication}" />
		</p:dialog>
		<p:dialog id="privacyDialog" header="Privacy"
			widgetVar="$privacyDialog" width="400" modal="true" dynamic="true">
			<h:outputText value="#{adminController.privacy}" />
		</p:dialog>
		<p:dialog id="disclaimerDialog" header="Disclaimer"
			widgetVar="$disclaimerDialog" width="400" modal="true" dynamic="true">
			<h:outputText value="#{adminController.disclaimer}" />
		</p:dialog>
		<p:dialog id="helpDialog" header="Help" widgetVar="$helpDialog"
			width="400" modal="true" dynamic="true">
			<h:outputText value="#{adminController.help}" />
		</p:dialog>
	</h:form>
</p:panel>
</html>

jobhub/src/main/webapp/templates/common/header.xhtml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
        xmlns:f="http://xmlns.jcp.org/jsf/core"
        xmlns:h="http://xmlns.jcp.org/jsf/html"
        xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
        xmlns:p="http://primefaces.org/ui"
        xmlns:pe="http://primefaces.org/ui/extensions">
    <p:panel>
    <h:form id="headerForm">
   <p:graphicImage value="/resources/images/logo/jobhub.png" width="250" height="95"  />   
	<p:carousel value="#{adminController.images}" var="image" pageLinks="6" autoPlayInterval="4000"   
        numVisible="1" effect="easeInStrong" circular="true" style="margin-left:12%">  
    <p:graphicImage value="/resources/images/galleria/#{image}" alt="Image Description for #{image}"  width="500" height="100"  title="#{image}"/>  
	</p:carousel>
	<p:outputPanel style="float:right" rendered="#{view.viewId == '/views/login.xhtml'}">
	<h:outputText value="#{msg['login.language']}: "  />  
        <h:selectOneMenu value="#{languageController.localeCode}" onchange="submit()" 
			valueChangeListener="#{languageController.countryLocaleCodeChanged}">
   			<f:selectItems value="#{languageController.countriesInMap}" />   
        </h:selectOneMenu>  
	</p:outputPanel>
	<p:outputPanel style="float:right" rendered="#{view.viewId != '/views/login.xhtml'}">
       <h:commandLink action="/views/login.xhtml?faces-redirect=true">  
            <p:graphicImage value="/resources/images/logout.png" />  
        </h:commandLink> 
	</p:outputPanel>
	</h:form>
	</p:panel> 
	
</html>