jobhub/src/main/java/com/packt/pfextensions/controller/JobhubTimelineController.java
package com.packt.pfextensions.controller;

import java.io.Serializable;
import java.util.Calendar;
import java.util.Date;
import java.util.TimeZone;

import javax.annotation.PostConstruct;
import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;
import javax.faces.context.FacesContext;

import org.primefaces.extensions.component.timeline.TimelineUpdater;
import org.primefaces.extensions.event.timeline.TimelineAddEvent;
import org.primefaces.extensions.event.timeline.TimelineModificationEvent;
import org.primefaces.extensions.event.timeline.TimelineSelectEvent;
import org.primefaces.extensions.model.timeline.TimelineEvent;
import org.primefaces.extensions.model.timeline.TimelineModel;

import com.packt.pfextensions.model.Jobhub;

@ManagedBean
@ViewScoped
public class JobhubTimelineController implements Serializable {

	/**
		 * 
		 */
	private static final long serialVersionUID = 1L;

	private boolean selectable = true;
	private boolean zoomable = true;
	private boolean moveable = true;
	private boolean stackEvents = true;
	private String eventStyle = "box";
	private boolean axisOnTop;
	private boolean showCurrentTime = true;
	private boolean showNavigation = false;

	private TimelineModel model;
	private TimelineEvent event;
	private long zoomMax;
	private Date start;
	private Date end;
	private TimeZone timeZone = TimeZone.getTimeZone("Europe/Madrid");

	@PostConstruct
	protected void initialize() {
		zoomMax = 1000L * 60 * 60 * 24 * 30;
		model = new TimelineModel();

		Calendar cal = Calendar.getInstance();
		cal.set(2011, Calendar.MAY, 10, 0, 0, 0);
		Date start = cal.getTime();
		cal.set(2011, Calendar.MAY, 15, 0, 0, 0);
		Date end = cal.getTime();

		model.add(new TimelineEvent(new Jobhub("10000", "500", "2000000"),
				start, end));

		cal.set(2012, Calendar.JANUARY, 23, 0, 0, 0);
		start = cal.getTime();
		cal.set(2012, Calendar.JANUARY, 28, 0, 0, 0);
		end = cal.getTime();

		model.add(new TimelineEvent(new Jobhub("7000", "700", "540000"), start,
				end));

		cal.set(2012, Calendar.APRIL, 2, 0, 0, 0);
		start = cal.getTime();
		cal.set(2012, Calendar.APRIL, 7, 0, 0, 0);
		end = cal.getTime();

		model.add(new TimelineEvent(new Jobhub("8000", "590", "2300000"),
				start, end));

		cal.set(2012, Calendar.APRIL, 16, 0, 0, 0);
		start = cal.getTime();
		cal.set(2012, Calendar.APRIL, 21, 0, 0, 0);
		end = cal.getTime();

		model.add(new TimelineEvent(new Jobhub("1000", "500", "8800000"),
				start, end));

		cal.set(2012, Calendar.MAY, 4, 0, 0, 0);
		start = cal.getTime();
		cal.set(2012, Calendar.MAY, 9, 0, 0, 0);
		end = cal.getTime();

		model.add(new TimelineEvent(new Jobhub("100", "590", "23000"), start,
				end));

		cal.set(2012, Calendar.MAY, 10, 0, 0, 0);
		start = cal.getTime();
		cal.set(2012, Calendar.MAY, 15, 0, 0, 0);
		end = cal.getTime();

		model.add(new TimelineEvent(new Jobhub("200", "500", "8800"), start,
				end));

		cal.set(2012, Calendar.MAY, 15, 0, 0, 0);
		start = cal.getTime();
		cal.set(2012, Calendar.MAY, 20, 0, 0, 0);
		end = cal.getTime();

		model.add(new TimelineEvent(new Jobhub("200", "590", "2300"), start,
				end));

		cal.set(2012, Calendar.MAY, 21, 0, 0, 0);
		start = cal.getTime();
		cal.set(2012, Calendar.MAY, 26, 0, 0, 0);
		end = cal.getTime();

		model.add(new TimelineEvent(new Jobhub("300", "500", "800"), start, end));

		cal.set(2012, Calendar.MAY, 26, 0, 0, 0);
		start = cal.getTime();
		cal.set(2012, Calendar.MAY, 31, 0, 0, 0);
		end = cal.getTime();

		model.add(new TimelineEvent(new Jobhub("200", "500", "8800"), start,
				end));

		cal.set(2012, Calendar.JUNE, 5, 0, 0, 0);
		start = cal.getTime();
		cal.set(2012, Calendar.JUNE, 10, 0, 0, 0);
		end = cal.getTime();

		model.add(new TimelineEvent(new Jobhub("10300", "500", "2000000"),
				start, end));

		cal.set(2012, Calendar.JUNE, 10, 0, 0, 0);
		start = cal.getTime();
		cal.set(2012, Calendar.JUNE, 15, 0, 0, 0);
		end = cal.getTime();

		model.add(new TimelineEvent(new Jobhub("60000", "500", "3300000"),
				start, end));

		cal.set(2012, Calendar.JUNE, 15, 0, 0, 0);
		start = cal.getTime();
		cal.set(2012, Calendar.AUGUST, 20, 0, 0, 0);
		end = cal.getTime();

		model.add(new TimelineEvent(new Jobhub("10300", "500", "2000000"),
				start, end));

		cal.set(2012, Calendar.JUNE, 19, 0, 0, 0);
		start = cal.getTime();
		cal.set(2012, Calendar.JULY, 24, 0, 0, 0);
		end = cal.getTime();

		model.add(new TimelineEvent(new Jobhub("60000", "500", "3300000"),
				start, end));

		cal.set(2012, Calendar.SEPTEMBER, 26, 0, 0, 0);
		start = cal.getTime();
		cal.set(2012, Calendar.SEPTEMBER, 31, 0, 0, 0);
		end = cal.getTime();

		model.add(new TimelineEvent(new Jobhub("34000", "700", "6000000"),
				start, end));

		cal.set(2012, Calendar.OCTOBER, 13, 0, 0, 0);
		start = cal.getTime();
		cal.set(2012, Calendar.OCTOBER, 18, 0, 0, 0);
		end = cal.getTime();

		model.add(new TimelineEvent(new Jobhub("15500", "700", "2000000"),
				start, end));

		cal.set(2012, Calendar.DECEMBER, 16, 0, 0, 0);
		start = cal.getTime();
		cal.set(2012, Calendar.DECEMBER, 21, 0, 0, 0);
		end = cal.getTime();

		model.add(new TimelineEvent(new Jobhub("23000", "600", "2300000"),
				start, end));

		cal.set(2013, Calendar.FEBRUARY, 3, 0, 0, 0);
		start = cal.getTime();
		cal.set(2013, Calendar.FEBRUARY, 8, 0, 0, 0);
		end = cal.getTime();

		model.add(new TimelineEvent(new Jobhub("23000", "500", "233000"),
				start, end));

		cal.set(2013, Calendar.MAY, 4, 0, 0, 0);
		start = cal.getTime();
		cal.set(2013, Calendar.MAY, 9, 0, 0, 0);
		end = cal.getTime();

		model.add(new TimelineEvent(new Jobhub("55000", "500", "2330000"),
				start, end));

		cal.set(2013, Calendar.JUNE, 5, 0, 0, 0);
		start = cal.getTime();
		cal.set(2013, Calendar.JUNE, 10, 0, 0, 0);
		end = cal.getTime();

		model.add(new TimelineEvent(new Jobhub("222000", "2300", "23230000"),
				start, end));
	}

	public void onChange(TimelineModificationEvent e) {
		event = e.getTimelineEvent();
		model.update(event);
		FacesMessage msg = new FacesMessage(FacesMessage.SEVERITY_INFO,
				"The Post details of posts count " + getJobhubPosts()
						+ " have been updated", null);
		FacesContext.getCurrentInstance().addMessage(null, msg);
	}

	public void onEdit(TimelineModificationEvent e) {
		event = e.getTimelineEvent();
	}

	public void onAdd(TimelineAddEvent e) {
		event = new TimelineEvent(new Jobhub(), e.getStartDate(),
				e.getEndDate(), true, e.getGroup());
		model.add(event);
	}

	public void onDelete(TimelineModificationEvent e) {
		event = e.getTimelineEvent();
	}

	public void delete() {
		TimelineUpdater timelineUpdater = TimelineUpdater
				.getCurrentInstance(":adminForm:tabView:timeline");
		model.delete(event, timelineUpdater);

		FacesMessage msg = new FacesMessage(FacesMessage.SEVERITY_INFO,
				"The posts details of posts count  " + getJobhubPosts()
						+ " has been deleted", null);
		FacesContext.getCurrentInstance().addMessage(null, msg);
	}

	public void saveDetails() {
		TimelineUpdater timelineUpdater = TimelineUpdater
				.getCurrentInstance(":adminForm:tabView:timeline");
		model.update(event, timelineUpdater);

		FacesMessage msg = new FacesMessage(FacesMessage.SEVERITY_INFO,
				"The posts details of posts count " + getJobhubPosts()
						+ " have been saved", null);
		FacesContext.getCurrentInstance().addMessage(null, msg);
	}

	public String getDeleteMessage() {
		String posts = ((Jobhub) event.getData()).getNoofposts();
		if (posts == null) {
			return "Do you really want to delete the jobhub event?";
		}

		return "Do you really want to delete the jobhub event for the posts count "
				+ posts + "?";
	}

	public String getJobhubPosts() {
		String posts = ((Jobhub) event.getData()).getNoofposts();
		if (posts == null) {
			return "(new jobhub event)";
		} else {
			return "(posts " + posts + ")";
		}
	}

	public TimelineModel getModel() {
		return model;
	}

	public boolean isSelectable() {
		return selectable;
	}

	public void setSelectable(boolean selectable) {
		this.selectable = selectable;
	}

	public boolean isZoomable() {
		return zoomable;
	}

	public void setZoomable(boolean zoomable) {
		this.zoomable = zoomable;
	}

	public boolean isMoveable() {
		return moveable;
	}

	public void setMoveable(boolean moveable) {
		this.moveable = moveable;
	}

	public boolean isStackEvents() {
		return stackEvents;
	}

	public void setStackEvents(boolean stackEvents) {
		this.stackEvents = stackEvents;
	}

	public String getEventStyle() {
		return eventStyle;
	}

	public void setEventStyle(String eventStyle) {
		this.eventStyle = eventStyle;
	}

	public boolean isAxisOnTop() {
		return axisOnTop;
	}

	public void setAxisOnTop(boolean axisOnTop) {
		this.axisOnTop = axisOnTop;
	}

	public boolean isShowCurrentTime() {
		return showCurrentTime;
	}

	public void setShowCurrentTime(boolean showCurrentTime) {
		this.showCurrentTime = showCurrentTime;
	}

	public boolean isShowNavigation() {
		return showNavigation;
	}

	public void setShowNavigation(boolean showNavigation) {
		this.showNavigation = showNavigation;
	}

	public TimelineEvent getEvent() {
		return event;
	}

	public void setEvent(TimelineEvent event) {
		this.event = event;
	}

	public long getZoomMax() {
		return zoomMax;
	}

	public Date getStart() {
		return start;
	}

	public Date getEnd() {
		return end;
	}

	public TimeZone getTimeZone() {
		return timeZone;
	}

}

jobhub/src/main/java/com/packt/pfextensions/controller/LoginBean.java
package com.packt.pfextensions.controller;

import java.io.Serializable;
import java.util.LinkedHashMap;
import java.util.Locale;
import java.util.Map;
import java.util.ResourceBundle;

import javax.annotation.PostConstruct;
import javax.faces.application.FacesMessage;
import javax.faces.context.FacesContext;
import javax.faces.event.ActionEvent;
import javax.faces.event.ValueChangeEvent;
import javax.faces.view.ViewScoped;
//import org.primefaces.context.RequestContext;
import javax.faces.bean.ManagedBean;


@ManagedBean
@ViewScoped
public class LoginBean implements Serializable{

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	private String username;
	
	private String password;
	
	private String userrole;
	private String loginmessage;
	private boolean renderRegister=true;
	ResourceBundle messageBundle;
	
	@PostConstruct  
	public void init() { 
		messageBundle = ResourceBundle.getBundle("com.packt.messages",FacesContext.getCurrentInstance().getViewRoot().getLocale());
		 loginmessage=messageBundle.getString("login.login"); 
	}
	
	public String validateUser() {
		FacesMessage msg = null;
		
		if(userrole.equalsIgnoreCase("2") && username != null && username.equals("admin") && password != null && password.equals("admin")) {
			return "/views/admin?faces-redirect=true";
		} else if(userrole.equalsIgnoreCase("1") && username != null && username.equals("employer") && password != null && password.equals("employer")) {
			return "/views/employerslist?faces-redirect=true";
		}
		else if(userrole.equalsIgnoreCase("0") && username != null && username.equals("jobseeker") && password != null && password.equals("jobseeker")){
			 return "/views/jobsList?faces-redirect=true";
		}
		else {
			msg = new FacesMessage(FacesMessage.SEVERITY_WARN, "Login Error", "Invalid credentials");
			FacesContext.getCurrentInstance().addMessage(null, msg);
			 return null;
		}
		
	}
	
	public void changeUserRole(){
		
		if(userrole.equalsIgnoreCase("1")){
			loginmessage=messageBundle.getString("login.employerlogin");
			renderRegister=false;

		}
		else if(userrole.equalsIgnoreCase("2")){
			loginmessage=messageBundle.getString("login.adminlogin");
			renderRegister=false;

		}
		else {
			loginmessage=messageBundle.getString("login.jobseekerlogin");
			renderRegister=true;

		}
		
	}
	
	
	public String getUsername() {
		return username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getPassword() {
		return password;
	}

	public void setPassword(String password) {
		this.password = password;
	}
	
	

	public String getUserrole() {
		return userrole;
	}

	public void setUserrole(String userrole) {
		this.userrole = userrole;
	}
	
	

	public String getLoginmessage() {
		return loginmessage;
	}

	public void setLoginmessage(String loginmessage) {
		this.loginmessage = loginmessage;
	}

	public boolean isRenderRegister() {
		return renderRegister;
	}

	public void setRenderRegister(boolean renderRegister) {
		this.renderRegister = renderRegister;
	}

	
}

jobhub/src/main/webapp/views/admin.xhtml
<!DOCTYPE html>
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:f="http://xmlns.jcp.org/jsf/core"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns:p="http://primefaces.org/ui"
	xmlns:pe="http://primefaces.org/ui/extensions"
	template="/templates/masterTemplate.xhtml">

	<ui:define name="content">
		<h:form id="adminForm">
			<p:tabView id="tabView">

				<p:tab id="tab1" title="Footer Configuration">
					<p:accordionPanel activeIndex="-1">
						<p:tab title="AboutUS">
							<h:panelGrid id="aboutusgrid" columns="2" cellpadding="10">
								<p:graphicImage value="/resources/images/aboutus.png" />
								<h:outputText value="#{adminController.aboutus}" />
							</h:panelGrid>
							<p:commandButton value="Edit"
								actionListener="#{adminController.aboutusEdit}"
								update="editor1panel"></p:commandButton>
							<p:outputPanel id="editor1panel">
								<pe:ckEditor id="editor1" value="#{adminController.aboutus}"
									toolbar="[['Cut','Copy','Paste','PasteText','PasteFromWord','-', 'SpellChecker']]"
									interfaceColor="\##{adminController.color}"
									rendered="#{adminController.aboutusFlag}" width="500" />
								<p:outputPanel rendered="#{adminController.aboutusFlag}">
									<p:colorPicker id="popupCP1" value="#{adminController.color}">
									</p:colorPicker>
									<p:commandButton value="Submit color" update="editor1" />
								</p:outputPanel>
								<p:commandButton value="Save"
									actionListener="#{adminController.aboutusSave}"
									update="editor1panel,aboutusgrid"
									rendered="#{adminController.aboutusFlag}"></p:commandButton>
							</p:outputPanel>
						</p:tab>
						<p:tab title="Communication">
							<h:panelGrid id="communicationgrid" columns="2" cellpadding="10">
								<p:graphicImage value="/resources/images/communication.png" />
								<h:outputText value="#{adminController.communication}" />
							</h:panelGrid>
							<p:commandButton value="Edit"
								actionListener="#{adminController.communicationEdit}"
								update="editor2panel"></p:commandButton>
							<p:outputPanel id="editor2panel">
								<pe:ckEditor id="editor2"
									value="#{adminController.communication}"
									toolbar="[['Cut','Copy','Paste','PasteText','PasteFromWord','-', 'SpellChecker']]"
									interfaceColor="\##{adminController.color}" width="500"
									rendered="#{adminController.communicationFlag}" />
								<p:outputPanel rendered="#{adminController.communicationFlag}">
									<p:colorPicker id="popupCP2" value="#{adminController.color}">
									</p:colorPicker>
									<p:commandButton value="Submit color" update="editor2" />
								</p:outputPanel>
								<p:commandButton value="Save"
									actionListener="#{adminController.communicationSave}"
									update="editor2panel,communicationgrid"
									rendered="#{adminController.communicationFlag}"></p:commandButton>

							</p:outputPanel>
						</p:tab>
						<p:tab title="Privacy">
							<h:panelGrid id="privacygrid" columns="2" cellpadding="10">
								<p:graphicImage value="/resources/images/privacy.png" />
								<h:outputText value="#{adminController.privacy}" />
							</h:panelGrid>
							<p:commandButton value="Edit"
								actionListener="#{adminController.privacyEdit}"
								update="editor3panel"></p:commandButton>
							<p:outputPanel id="editor3panel">
								<pe:ckEditor id="editor3" value="#{adminController.privacy}"
									toolbar="[['Cut','Copy','Paste','PasteText','PasteFromWord','-', 'SpellChecker']]"
									interfaceColor="\##{adminController.color}" width="500"
									rendered="#{adminController.privacyFlag}" />
								<p:outputPanel rendered="#{adminController.privacyFlag}">
									<p:colorPicker id="popupCP3" value="#{adminController.color}">
									</p:colorPicker>
									<p:commandButton value="Submit color" update="editor3" />
								</p:outputPanel>
								<p:commandButton value="Save"
									actionListener="#{adminController.privacySave}"
									update="editor3panel,privacygrid"
									rendered="#{adminController.privacyFlag}"></p:commandButton>

							</p:outputPanel>
						</p:tab>
						<p:tab title="Disclaimer">
							<h:panelGrid id="disclaimergrid" columns="2" cellpadding="10">
								<p:graphicImage value="/resources/images/disclaimer.png" />
								<h:outputText value="#{adminController.disclaimer}" />
							</h:panelGrid>
							<p:commandButton value="Edit"
								actionListener="#{adminController.disclaimerEdit}"
								update="editor4panel"></p:commandButton>
							<p:outputPanel id="editor4panel">
								<pe:ckEditor id="editor4" value="#{adminController.disclaimer}"
									toolbar="[['Cut','Copy','Paste','PasteText','PasteFromWord','-', 'SpellChecker']]"
									interfaceColor="\##{adminController.color}" width="500"
									rendered="#{adminController.disclaimerFlag}" />
								<p:outputPanel rendered="#{adminController.disclaimerFlag}">
									<p:colorPicker id="popupCP4" value="#{adminController.color}">
									</p:colorPicker>
									<p:commandButton value="Submit color" update="editor4" />
								</p:outputPanel>
								<p:commandButton value="Save"
									actionListener="#{adminController.disclaimerSave}"
									update="editor4panel,disclaimergrid"
									rendered="#{adminController.disclaimerFlag}"></p:commandButton>

							</p:outputPanel>
						</p:tab>
						<p:tab title="Help">
							<h:panelGrid id="helpgrid" columns="2" cellpadding="10">
								<p:graphicImage value="/resources/images/help.png" />
								<h:outputText value="#{adminController.help}" />
							</h:panelGrid>
							<p:commandButton value="Edit"
								actionListener="#{adminController.helpEdit}"
								update="editor5panel"></p:commandButton>
							<p:outputPanel id="editor5panel">
								<pe:ckEditor id="editor5" value="#{adminController.help}"
									toolbar="[['Cut','Copy','Paste','PasteText','PasteFromWord','-', 'SpellChecker']]"
									interfaceColor="\##{adminController.color}" width="500"
									rendered="#{adminController.helpFlag}" />
								<p:outputPanel rendered="#{adminController.helpFlag}">
									<p:colorPicker id="popupCP5" value="#{adminController.color}">
									</p:colorPicker>
									<p:commandButton value="Submit color" update="editor5" />
								</p:outputPanel>
								<p:commandButton value="Save"
									actionListener="#{adminController.helpSave}"
									update="editor5panel,helpgrid"
									rendered="#{adminController.helpFlag}"></p:commandButton>

							</p:outputPanel>
						</p:tab>
					</p:accordionPanel>
				</p:tab>
				<p:tab id="tab2" title="Jobhub Timeline">
					<pe:timeline id="timeline"
						value="#{jobhubTimelineController.model}" height="250px"
						var="jobhub" selectable="#{jobhubTimelineController.selectable}"
						zoomable="#{jobhubTimelineController.zoomable}"
						moveable="#{jobhubTimelineController.moveable}"
						stackEvents="#{jobhubTimelineController.stackEvents}"
						axisOnTop="#{jobhubTimelineController.axisOnTop}"
						eventStyle="#{jobhubTimelineController.eventStyle}"
						showCurrentTime="#{jobhubTimelineController.showCurrentTime}"
						showNavigation="#{jobhubTimelineController.showNavigation}"
						timeZone="#{jobhubTimelineController.timeZone}"
						zoomMax="#{jobhubTimelineController.zoomMax}"
						start="#{jobhubTimelineController.start}"
						end="#{jobhubTimelineController.end}" editable="true"
						showButtonNew="true" minHeight="200" widgetVar="timelineWdgt">

						<p:ajax event="change" update="@none"
							listener="#{jobhubTimelineController.onChange}" />
						<p:ajax event="edit" update=":jobhubdetails:detailsJobhubInner"
							listener="#{jobhubTimelineController.onEdit}"
							oncomplete="PF('detailsJobhubWdgt').show()" />
						<p:ajax event="add" update=":jobhubdetails:detailsJobhubInner"
							listener="#{jobhubTimelineController.onAdd}"
							oncomplete="PF('detailsJobhubWdgt').show()" />
						<p:ajax event="delete" update=":deletejobhub:deleteJobhubInner"
							listener="#{jobhubTimelineController.onDelete}"
							onstart="PF('timelineWdgt').cancelDelete()"
							oncomplete="PF('deleteJobhubWdgt').show()" />


						<h:panelGrid columns="1">
							<h:outputText value="Posts: #{jobhub.noofposts}" />
							<h:outputText value="Employers: #{jobhub.noofemployers}" />
							<h:outputText value="AppliedPosts: #{jobhub.noofappliedposts}" />
						</h:panelGrid>
					</pe:timeline>

					<h:outputStylesheet id="timelineCSS">
    table .formColumn {
        padding: 0 5px 0 20px;
        text-align: right;
        white-space: nowrap;
    }       
</h:outputStylesheet>

				</p:tab>


			</p:tabView>
		</h:form>
		<p:dialog id="detailsJobhubDlg" header="Jobhub Details"
			widgetVar="detailsJobhubWdgt" showEffect="clip" hideEffect="clip"
			appendToBody="true">
			<h:form id="jobhubdetails">
			    <p:messages></p:messages>
				<h:panelGroup id="detailsJobhubInner" layout="block">
					<h:panelGrid columns="2"
						columnClasses="JobhubDetails1,JobhubDetails2">
						<h:outputText value="Posts" />
						<p:inputText
							value="#{jobhubTimelineController.event.data.noofposts}"
							required="true" label="Posts" />

						<h:outputText value="Start" />
						<p:calendar value="#{jobhubTimelineController.event.startDate}"
							timeZone="#{jobhubTimelineController.timeZone}"
							pattern="dd/MM/yyyy HH:mm" required="true" label="From" />

						<h:outputText value="End" />
						<p:calendar value="#{jobhubTimelineController.event.endDate}"
							timeZone="#{jobhubTimelineController.timeZone}"
							pattern="dd/MM/yyyy HH:mm" label="Until" />

						<h:outputText value="Employers" />
						<p:inputText
							value="#{jobhubTimelineController.event.data.noofemployers}"
							required="true" label="Employers" />

						<h:outputText value="Applied posts" />
						<p:inputText
							value="#{jobhubTimelineController.event.data.noofappliedposts}"
							required="true" label="Applied Posts" />
					</h:panelGrid>
				</h:panelGroup>
				<p:separator></p:separator>
				<h:panelGroup layout="block"
					style="text-align:right; padding:2px; white-space:nowrap;">
					<p:commandButton value="Save" process="@this,jobhubdetails"
						update=":jobhubdetails"
						action="#{jobhubTimelineController.saveDetails}"
						oncomplete="if(!args.validationFailed){PF('detailsJobhubWdgt').hide();}" />
					<p:commandButton type="button" value="Close"
						onclick="PF('detailsJobhubWdgt').hide()" />
				</h:panelGroup>
			</h:form>
		</p:dialog>

		<p:dialog id="deleteJobhubDlg" header="Jobhub Details"
			widgetVar="deleteJobhubWdgt" showEffect="clip" hideEffect="clip"
			appendToBody="true" dynamic="true">
			<h:form id="deletejobhub">
				<h:panelGroup id="deleteJobhubInner" layout="block"
					style="margin:10px;">
					<h:outputText value="#{jobhubTimelineController.deleteMessage}" />
				</h:panelGroup>

				<p:separator></p:separator>
				<h:panelGroup layout="block"
					style="text-align:right; padding:2px; white-space:nowrap;">
					<p:commandButton value="Delete" process="deletejobhub"
						update="@none" action="#{jobhubTimelineController.delete}"
						oncomplete="PF('deleteJobhubWdgt').hide()" />
					<p:commandButton type="button" value="Close"
						onclick="PF('deleteJobhubWdgt').hide()" />
				</h:panelGroup>
			</h:form>
		</p:dialog>
	</ui:define>
</ui:composition>